### PR TITLE
add astar portal button to the header

### PR DESCRIPTION
**Pull request by ayumitk**
**Pull Request Summary**

Screenshot 2024-04-25 at 9 29 40 AM

- Added the "Astar Portal" button to the header

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Review by gtg7784 — APPROVED** [review]
LGTM!

**Comment by gtg7784** [comment]
btw, are you using some sorting extension or plugin for tailwindcss? some of the classes are sorted @ayumitk

**Comment by ayumitk** [comment]
@gtg7784 Ah, sorry. I kept enabling the plugin [Tailwind Raw Reorder](https://marketplace.visualstudio.com/items?itemName=Trapfether.tailwind-raw-reorder) in VScode while I edited the files. I think it might be better to use [prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) or something and include its config file in the repo.

**Comment by gtg7784** [comment]
> @gtg7784 Ah, sorry. I kept enabling the plugin [Tailwind Raw Reorder](https://marketplace.visualstudio.com/items?itemName=Trapfether.tailwind-raw-reorder) in VScode while I edited the files. I think it might be better to use [prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) or something and include its config file in the repo.

Oh, it is just a curious. That’s good! I’ll check some prettier plug-in or eslint plugin for ordering classname.

**Review by impelcrypto — APPROVED** [review]

**Review by bobo-k2 — COMMENTED** [review]
Looks good to me, but for some reason I don't have an option to approve the PR 
image

**Comment by bobo-k2** [comment]
I figured out. The PR is already merged :)

**Pull request merged**
