### PR TITLE
merge new frontend

### PR DESCRIPTION
**Pull request by ayumitk**
revert #81 and fixed conflict

### CODE REVIEW

**Review by ehsanhajian — COMMENTED** [review]
@ayumitk I think something is wrong as CI failed to deploy it. I think Directory structure is not correct.

**Comment by ayumitk** [comment]
@ehsanhajian The current file structure is below, the same as the [ecosystem-page](https://github.com/AstarNetwork/astarwebsite_v2/tree/ecosystem-page) branch we used for the [preview](http://astar-git.astar.network.s3-website-ap-northeast-1.amazonaws.com/).
```
root/
├── backend/
├── frontend/
```

In my local machine with the `revert-81-ecosystem-page` branch, I run:
```
cd frontend/
npm run generate
serve .output/public/
```
then, it worked. I can't see what's wrong.

I know you told me to ignore the `.github/workflows`, but CI tried to run on the `root` directory instead of the `frontend/` directory. Isn't this the reason? (Sorry if my guess sounded dumb)

**Comment by ehsanhajian** [comment]
@ayumitk so I need to change CI. but do you think we need backend directory on the repo? since we are not going to change Strapi code.

**Comment by ayumitk** [comment]
@ehsanhajian 

> do you think we need backend directory on the repo? since we are not going to change Strapi code.

No, I don't think we need the `backend` directory for this PR. (sooner or later, we'll merge the `backend` directory to the main branch, I guess)

Oh, so you meant that I should modify the file structure like the below? (remove the `backend` folder and spread `frontend` folder to the root, then we don't need to change CI?)
```
Current:
root/
├── backend/
├── frontend/

↓

After:
root/
├── assets/
├── components/
├── pages/
...
```

**Comment by ehsanhajian** [comment]
yes. like the current structure that we have in the main repo. @ayumitk.

**Comment by ayumitk** [comment]
@ehsanhajian Fixed the file structure. Sorry, I completely misunderstood.

**Review by ehsanhajian — APPROVED** [review]
thank you. @ayumitk

**Pull request merged**
